@startuml
skinparam classAttributeIconSize 0
class PrintJob{
- doc : Document
- {static} jobIdCounter : int
- jobId : int
+ PrintJob(doc : Document)
+ getContent() : String[]
+ toString() : String
+ getJobId() : int
+ getDocument() : Document
+ call() : String[]
}
PrintJob ..|> Callable
class PrinterTest{
- {static} pause(millis : long) : void
+ {static} main(args : String[]) : void
}
class AdvancedPrinter{
- spool : PrinterService
+ AdvancedPrinter()
+ print(doc : Document) : int
+ print(docs : List<Document>) : List<Integer>
+ showQueuedJobs() : void
+ cancelJob(jobId : int) : boolean
+ cancelAll() : void
}
AdvancedPrinter ..|> AdvancedPrinterInterface
class BasicPrinter{
- inkAmount : int
- paperAmount : int
+ BasicPrinter()
+ print(content : String[]) : boolean
+ hasInk() : boolean
+ hasPaper() : boolean
+ addInk() : void
+ addPaper() : void
+ refill() : void
}
class Document{
- fp : Scanner
- filename : String
+ Document(filename : String)
+ hasNextLine() : boolean
+ readLine() : String
+ reopen() : void
}
class BasicPrinterAdapter{
- basicPrinter : BasicPrinter
+ BasicPrinterAdapter(basicPrinter : BasicPrinter)
}
BasicPrinterAdapter --|> AdvancedPrinter
class PrinterService{
- printQueue : LinkedBlockingQueue<PrintJob>
- pool : ExecutorService
+ PrinterService()
+ run() : void
+ newPrintJob(doc : Document) : int
+ cancelJob(job : int) : boolean
shutdownAndAwaitTermination() : void
+ getPrintQueue() : LinkedBlockingQueue<PrintJob>
}
PrinterService ..|> Runnable
PrintJob--"- doc" Document
AdvancedPrinter--"- spool" PrinterService
BasicPrinterAdapter--"- basicPrinter" BasicPrinter
interface AdvancedPrinterInterface{
+ print(doc : Document) : int
+ print(docs : List<Document>) : List<Integer>
+ showQueuedJobs() : void
+ cancelJob(jobId : int) : boolean
+ cancelAll() : void
}
@enduml